"""Agregar índices a numero y ci

Revision ID: e5892d8c1345
Revises: 
Create Date: 2025-03-29 16:35:11.477382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5892d8c1345'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voto_ci'), ['ci'], unique=True)
        batch_op.create_index(batch_op.f('ix_voto_numero'), ['numero'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voto_numero'))
        batch_op.drop_index(batch_op.f('ix_voto_ci'))

    # ### end Alembic commands ###
